turingPrueba/Controllers/WriterController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using turingPrueba.Extensions;
using turingPrueba.Models;
using turingPrueba.Permissions;
using turingPrueba.Service;

namespace turingPrueba.Controllers
{
    public class WriterController : Controller
    {
        public const string SessionId = "_IdUser";
        private readonly ILogger<WriterController> _logger;
        private readonly IEditorialRepository _editorialRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IBookRepository _bookRepository;

        public WriterController(ILogger<WriterController> logger, IEditorialRepository editorialRepository, ICategoryRepository categoryRepository, IBookRepository bookRepository)
        {
            _logger = logger;
            _categoryRepository = categoryRepository;
            _editorialRepository = editorialRepository;
            _bookRepository = bookRepository;
        }
        public async Task<IndexWriterViewModel> GetModelIndex()
        {
            var idUser = HttpContext.Session.Get<int>(SessionId);
            var model = new IndexWriterViewModel();
            var editorialList = await _editorialRepository.getAll();
            var categoryList = await _categoryRepository.getAll();
            var books = await _bookRepository.GetByUSer(idUser);
            var categories = await _bookRepository.GetByCategory();
            if (editorialList is not null)
            {
                model.EditorialList = editorialList.Select(
                    x => new SelectListItem { Text = x.Name, Value = x.IdEditorial.ToString() }
                ).ToList();
            }
            if (categoryList is not null)
            {
                model.CategoryList = categoryList.Select(
                    x => new SelectListItem { Text = x.Name, Value = x.IdCategory.ToString() }
                ).ToList();
            }
            if (books is not null)
            {
                model.BooksByUser = books;
            }
            if (categories is not null)
            {
                model.BooksByCategories= categories;
            }
            return model;
        }

        [ValidateSession]
        [Authorize(Roles = "writer")]
        public async Task<IActionResult> Index()
        {
            var model = await GetModelIndex();
            return View(model);
        }
        [ValidateSession]
        [Authorize(Roles = "writer")]
        public async Task<IActionResult> AddBook(Book book)
        {
            var model = await GetModelIndex();
            if (!ModelState.IsValid)
            {
                return View("Index", model);
            }
            book.UserId = HttpContext.Session.Get<int>(SessionId).ToString();
            TempData["response"] = await _bookRepository.Save(book);
            TempData["type"] = 1;

            return RedirectToAction("Index", model);
        }

        [ValidateSession]
        [Authorize(Roles = "writer")]
        public async Task<IActionResult> Delete(long id)
        {
            var model = await GetModelIndex();
            TempData["response"] = await _bookRepository.DeleteById(id);
            TempData["type"] = 3;

            return RedirectToAction("Index", model);
        }

        [ValidateSession]
        [Authorize(Roles = "writer")]
        public async Task<IActionResult> UpdateBook(long id)
        {
            var model = await GetModelIndex();
            var book = await _bookRepository.GetById(id);
            if (book is not null)
            {
                model.IdBook = book.IdBook;
                model.Title = book.Title;
                model.Subtitle = book.Subtitle;
                model.Pages = book.Pages;
                model.Isbn = book.Isbn;
                model.CategoryId = book.CategoryId;
                model.EditorialId = book.EditorialId;
            }

            return View(model);
        }
        [ValidateSession]
        [Authorize(Roles = "writer")]
        [HttpPost]
        public async Task<IActionResult> UpdateBook(Book book)
        {
            var model = await GetModelIndex();
            if (!ModelState.IsValid)
            {
                return View("Index", model);
            }            
            TempData["response"] = await _bookRepository.Update(book);
            TempData["type"] = 2;
            return RedirectToAction("Index", model);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

turingPrueba/Views/Writer/Index.cshtml
@model IndexWriterViewModel


<link rel="stylesheet" href="~/css/card.css" />


<section style="background-color: #112E40; padding: 25px;">
  <figure class="text-center" style="color:#FFF">
    <blockquote class="blockquote">
      <p>Aplicación libreria</p>
    </blockquote>
    <figcaption class="blockquote-footer" style="color:#FFF">
      Visualiza y agrega nuevos libros
    </figcaption>
  </figure>
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-3">
        <h1 style="color:#FFFFFF;">Mis libros</h1>
      </div>
      <div class="col-3">
        <button class="btn-registrer" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">Registrar
          nuevo libro</button>
      </div>
    </div>

    <div class="row">
      @if (Model.BooksByUser.Count() > 0)
      {
        @foreach(var book in Model.BooksByUser){
          <div class="filter-result col-md-4">
            <div class="job-box d-md-flex align-items-center justify-content-between mb-30">
              <div class="job-left my-4 d-md-flex align-items-center flex-wrap">
                <div class="img-holder mr-md-4 mb-md-0 mb-4 mx-auto mx-md-0 d-md-none d-lg-flex">
                  BO
                </div>
                <div class="job-content">
                  <h5 class="text-center text-md-left">Libro</h5>
                  <ul class="d-md-flex flex-wrap text-capitalize ff-open-sans">
                    <li class="mr-md-4">
                      <b>Titulo: </b>@book.Title
                    </li>
                    <li class="mr-md-4">
                      <b>Subtitulo: </b>@book.Subtitle
                    </li>
                    <li class="mr-md-4">
                      <b>Editorial: </b>@book.EditorialId
                    </li>
                    <li class="mr-md-4">
                      <b>Categoria: </b>@book.CategoryId
                    </li>
                    <li class="mr-md-4">
                      <b>Paginas: </b>@book.Pages                      
                    </li>
                    <li class="mr-md-4">
                      <b>ISBN: </b>@book.Isbn                      
                    </li>
                  </ul>
                </div>
                <a class="btn-customer" asp-controller="Writer" asp-route-id="@book.IdBook" asp-action="UpdateBook">Editar</a>
                <a type="button" asp-controller="Writer" asp-route-id="@book.IdBook" asp-action="Delete" class="btn_negative">Eliminar</a>
              </div>
            </div>
          </div>
        }
      }else{
        <br>
        <div class="alert alert-primary" role="alert">
            <span class="text-wrap">Sin registros</span>
        </div>
      }
      
      
      
    </div>

    
  </div>
</section>
<section style="background-color: #C7D2D9; padding: 25px;">
  <div class="row">
    @if(Model.BooksByCategories.Count()>0){
      @foreach(var category in Model.BooksByCategories){
        <p class="h3">@category.Name</p>
        <hr class="hr" />
        @foreach(var book in category.books){
          <div class="col-sm-6 col-lg-4 col-xl-3 mb-4">
            <div class="card">
              <img src="https://www.elindependiente.com/wp-content/uploads/2022/12/Tostonazo-Santiago-Lorenzo-421x660.png"
                class="card-img-top">
              <div class="card-body">
                <h5 class="card-title">@book.Title</h5>
                <p class="lead">
                  @book.Subtitle
                </p>
                
                <div class="row">
                  <p class="col-md-6"><strong>@book.EditorialId</strong></p>
                  <p class="col-md-6"><strong>@book.UserId</strong></p>
                </div>
                <div class="row">
                  <p class="col-md-6">ISBN: @book.Isbn</p>
                  <p class="col-md-6">Paginas: @book.Pages</p>
                </div>
              </div>
            </div>
          </div>
        }
      }
    }
    
  </div>

</section>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <form asp-action="AddBook" asp-controller="Writer">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Registro Libro</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

          <div class="row">
            <div class="col-md-6">
              <label>Titulo</label>
              <input type="text" class="form-control" asp-for="Title" />
              <span class="text-danger" asp-validation-for="Title" val></span>
            </div>
            <div class="col-md-6">
              <label>Subtitulo</label>
              <input type="text" class="form-control" asp-for="Subtitle" />
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <label>No. Paginas</label>
              <input type="number" class="form-control" asp-for="Pages" />
              <span class="text-danger" asp-validation-for="Pages"></span>
            </div>
            <div class="col-md-6">
              <label>ISBN</label>
              <input type="text" class="form-control" asp-for="Isbn" />
              <span class="text-danger" asp-validation-for="Isbn"></span>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <label class="form-label">Categoria</label>
              <select class="form-select" aria-label="Default select example" asp-for="CategoryId"
                asp-items="@Model.CategoryList">
                <option value="">Seleccione una opción</option>
                
              </select>
              <span class="text-danger" asp-validation-for="CategoryId"></span>
              <span class="text-danger"></span>
            </div>
            <div class="col-md-6">
              <label class="form-label">Editorial</label>
              <select class="form-select" aria-label="Default select example" asp-for="EditorialId"
                asp-items="@Model.EditorialList">
                <option value="">Seleccione una opción</option>
              </select>
              <span class="text-danger" asp-validation-for="EditorialId"></span>
              <span class="text-danger"></span>
            </div>

          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="close-modal" data-bs-dismiss="modal">cerrar</button>
          <button type="submit" class="btn-registrer" >guardar</button>
        </div>
      </form>
    </div>
  </div>
</div>



@section Scripts
{
<script src="~/js/card.js"></script>
<partial name="_ValidationScriptsPartial" />
<script>
  let response = 0;
  let type = 0;

  const Toast = Swal.mixin({
    toast: true,
    position: 'top-end',
    showConfirmButton: false,
    timer: 7000,
    timerProgressBar: true,
    didOpen: (toast) => {
      toast.addEventListener('mouseenter', Swal.stopTimer)
      toast.addEventListener('mouseleave', Swal.resumeTimer)
    }
  });
  $(document).ready(function () {

  })

  response = @(TempData["response"] == null ? "null" : TempData["response"]);
  type = @(TempData["type"] == null ? "null" : TempData["type"]);


  switch (type) {
    case 1:
      if (response > 0) {
        Toast.fire({
          icon: 'success',
          title: '¡Registro exitoso!'
        })
      } else if (response === 0) {
        Toast.fire({
          icon: 'error',
          title: '¡Algo ocurrió, intenta nuevamente!'
        })
      }
      break;
    case 2:
      if (response > 0) {
        Toast.fire({
          icon: 'success',
          title: '¡Actualización exitosa!'
        })
      } else if (response === 0) {
        Toast.fire({
          icon: 'error',
          title: '¡Algo ocurrió, intenta nuevamente!'
        })
      }
      break;
    case 3:
      if (response > 0) {
        Toast.fire({
          icon: 'success',
          title: '¡Eliminación exitosa!'
        })
      } else if (response === 0) {
        Toast.fire({
          icon: 'error',
          title: '¡Algo ocurrió, intenta nuevamente!'
        })
      }
      break;
    case 4:
      if (response > 0) {
        Toast.fire({
          icon: 'success',
          title: '¡Bienvenido  !'
        })
      }
      break;
    case 5:
      Toast.fire({
        icon: 'error',
        title: '¡No se encontro el recurso!'
      })
      break;
    default:
      break;
  }
</script>
}

turingPrueba/Views/Writer/UpdateBook.cshtml
@model IndexWriterViewModel

<section style="background-color: #112E40; padding: 25px;">
    <div class="container ">
        <h1 class="display-6" style="color: #FFFF;">Actuaizar Libro</h1>
        <div class="card cascading-right" style="
            background:#FFFF;
            backdrop-filter: blur(30px);
            padding: 50px;
            ">
            <form asp-controller="Writer" asp-action="UpdateBook" method="post">
                <input hidden asp-for="IdBook">
                <div class="row">
                    <div class="col-md-6">
                        <label>Titulo</label>
                        <input type="text" class="form-control" asp-for="Title" />
                        <span class="text-danger" asp-validation-for="Title" val></span>
                    </div>
                    <div class="col-md-6">
                        <label>Subtitulo</label>
                        <input type="text" class="form-control" asp-for="Subtitle" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label>No. Paginas</label>
                        <input type="number" class="form-control" asp-for="Pages" />
                        <span class="text-danger" asp-validation-for="Pages"></span>
                    </div>
                    <div class="col-md-6">
                        <label>ISBN</label>
                        <input type="text" class="form-control" asp-for="Isbn" />
                        <span class="text-danger" asp-validation-for="Isbn"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label class="form-label">Categoria</label>
                        <select class="form-select" aria-label="Default select example" asp-for="CategoryId"
                            asp-items="@Model.CategoryList">
                            <option value="">Seleccione una opción</option>

                        </select>
                        <span class="text-danger" asp-validation-for="CategoryId"></span>
                        <span class="text-danger"></span>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label">Editorial</label>
                        <select class="form-select" aria-label="Default select example" asp-for="EditorialId"
                            asp-items="@Model.EditorialList">
                            <option value="">Seleccione una opción</option>
                        </select>
                        <span class="text-danger" asp-validation-for="EditorialId"></span>
                        <span class="text-danger"></span>
                    </div>
                    <br>
                    <br>
                    <br>
                    <div class="d-grid gap-2 col-6 mx-auto">
                        <button class="btn-registrer" type="submit"
                           >Actualizar</button>
                    </div>
            </form>
        </div>
    </div>
</section>